# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
    [
      {id: 0, size: 1.0, name: april_tag_0},
      {id: 1, size: 1.0, name: april_tag_1},
      {id: 2, size: 1.0, name: april_tag_2},
      {id: 3, size: 1.0, name: april_tag_3},
      {id: 4, size: 1.0, name: april_tag_4},
      {id: 5, size: 1.0, name: april_tag_5},
      {id: 10, size: 1.0, name: boat0_tag_0},
      {id: 11, size: 1.0, name: boat0_tag_1},
      {id: 12, size: 1.0, name: boat0_tag_2},
      {id: 13, size: 1.0, name: boat0_tag_3},
      {id: 20, size: 1.0, name: boat1_tag_0},
      {id: 21, size: 1.0, name: boat1_tag_1},
      {id: 22, size: 1.0, name: boat1_tag_2},
      {id: 23, size: 1.0, name: boat1_tag_3}
    ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
